# Generated by Django 5.2 on 2025-07-19 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_imagechambre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
